### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AdrienJarretier** [AdrienJarretier/Rout-Ine#1]
- [ ] Barre de recherche bénéficiaires
- [ ] Édition manuelle
  - [ ] Édition de la localisation des adresses
  - [ ] modifier l'affectation des tournées manuellement, ainsi que l'ordre de modification pour 
  - [ ] Rajouter tables pour modifications utilisateurs ce qui permettre de revenir en arrière, enregistrer dateTime pouvoir reculer
- [x] Initialisation des tournées : interface de progression
- [x] Gérer l'ajout d'adresses quand les tournées sont déjà affectées au moment du téléchargement de la tournée
- [x] nommer les tournées, légende couleur
- [x] Gérer la tournée extérieur Albi
- [x] tableau récapitulatif repas normaux / repas régimes par tournée / nombre de livraisons
- [ ] La tournée extérieure doit conserver son ordre
- [x] Export csv des tournées
- [ ] interface pour sélectionner les ville extérieures à inclure dans les tournées albigeoises
- [ ] Export csv des logs
---
- [x] autentification ldap
- [x] http://expressjs.com/en/resources/middleware/session.html
- [ ] Centre ville à livrer en priorité (avant 9h), départ à 7h donc 2h pour livrer centre ville
- [ ] Visualiser les logs de livraisons validées
- [ ] Download du zip avec la carte
